services:
  app:
    build: ./infra/php
    user: "1000:1000"
    volumes:
      - ./src:/data
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - 5173:5173
    restart: unless-stopped
    networks:
      - app-network

  web:
    image: nginx:1.25-alpine
    ports:
      - 80:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - app-network

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - TZ=Asia/Tokyo
    restart: unless-stopped
    networks:
      - app-network

volumes:
  db-store:

networks:
  app-network:
    driver: bridge
